import { useEffect, useState, useCallback } from 'react';

type Locale = 'en' | 'id';

const translations: Record<Locale, Record<string, string>> = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory',
    'nav.addItem': 'Add Item',
    'nav.analytics': 'Analytics',
    'nav.transactions': 'Transactions',
    'nav.alerts': 'Alerts',
    'nav.restock': 'Restock Predictions',
    'nav.journal': 'Finance Journal',
    'nav.settings': 'Settings',
    'nav.share': 'Share',
    'common.title': 'InvenSight',
    'common.subtitle': 'Inventory & Stock Visibility OS',
    'common.welcome': 'Welcome back',
    'common.loading': 'Loading...',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.category': 'Category',
    'common.location': 'Location',
    'common.supplier': 'Supplier',
    'common.stock': 'Stock',
    'common.minStock': 'Min Stock',
    'common.maxStock': 'Max Stock',
    'common.cost': 'Cost',
    'common.price': 'Price',
    'common.totalValue': 'Total Value',
    'common.quantity': 'Quantity',
    'common.date': 'Date',
    'common.action': 'Action',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.none': 'None',
    'common.lowStock': 'Low Stock',
    'common.overstock': 'Overstock',
    'common.expiring': 'Expiring Soon',
    'common.reorder': 'Reorder Recommended',
    'dashboard.totalItems': 'Total Items',
    'dashboard.lowStock': 'Low Stock Items',
    'dashboard.overstock': 'Overstock Items',
    'dashboard.totalValue': 'Total Inventory Value',
    'dashboard.expiringSoon': 'Expiring Soon',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.restockAlerts': 'Restock Alerts',
    'inventory.items': 'Inventory Items',
    'inventory.addNew': 'Add New Item',
    'inventory.editItem': 'Edit Item',
    'inventory.deleteConfirm': 'Delete this item permanently?',
    'inventory.stockLevel': 'Stock Level',
    'inventory.low': 'Low',
    'inventory.normal': 'Normal',
    'inventory.high': 'High',
    'inventory.addTransaction': 'Add Transaction',
    'inventory.transactionIn': 'Stock In',
    'inventory.transactionOut': 'Stock Out',
    'inventory.transactionAdjust': 'Adjustment',
    'inventory.transactionReturn': 'Return',
    'analytics.title': 'Analytics Dashboard',
    'analytics.stockDistribution': 'Stock Distribution',
    'analytics.categoryBreakdown': 'Category Breakdown',
    'analytics.trends': 'Inventory Trends',
    'analytics.sourceAttribution': 'Traffic Sources',
    'analytics.financeSummary': 'Finance Summary',
    'analytics.topMoving': 'Top Moving Items',
    'analytics.exportPdf': 'Export PDF Report',
    'analytics.exportExcel': 'Export Excel',
    'analytics.noData': 'No data available',
    'transactions.title': 'Transaction History',
    'transactions.add': 'Add Transaction',
    'transactions.filterBy': 'Filter by',
    'transactions.allTypes': 'All Types',
    'transactions.stockIn': 'Stock In',
    'transactions.stockOut': 'Stock Out',
    'transactions.adjustment': 'Adjustment',
    'transactions.return': 'Return',
    'alerts.title': 'Alerts Center',
    'alerts.lowStock': 'Low Stock Alert',
    'alerts.overstock': 'Overstock Alert',
    'alerts.expiring': 'Expiring Soon Alert',
    'alerts.reorder': 'Reorder Recommendation',
    'alerts.markRead': 'Mark as Read',
    'alerts.markAllRead': 'Mark All as Read',
    'alerts.empty': 'No alerts',
    'restock.title': 'Restock Predictions',
    'restock.predictedDate': 'Predicted Restock Date',
    'restock.confidence': 'Confidence',
    'restock.low': 'Low',
    'restock.medium': 'Medium',
    'restock.high': 'High',
    'restock.empty': 'No restock predictions',
    'journal.title': 'Finance Journal',
    'journal.entry': 'Journal Entry',
    'journal.addEntry': 'Add Entry',
    'journal.source': 'Source',
    'journal.description': 'Description',
    'journal.amount': 'Amount',
    'journal.type': 'Type',
    'journal.income': 'Income',
    'journal.expense': 'Expense',
    'journal.autoTask': 'Auto Task',
    'journal.autoBill': 'Auto Bill',
    'journal.autoTendor': 'Auto Vendor',
    'journal.manual': 'Manual',
    'journal.posted': 'Posted',
    'journal.pending': 'Pending',
    'journal.cancelled': 'Cancelled',
    'journal.totalIncome': 'Total Income',
    'journal.totalExpense': 'Total Expense',
    'journal.balance': 'Balance',
    'journal.exportPdf': 'Export PDF',
    'journal.exportExcel': 'Export Excel',
    'journal.empty': 'No journal entries',
    'settings.title': 'Settings',
    'settings.theme': 'Theme',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.financeTracking': 'Finance Tracking',
    'settings.about': 'About',
    'settings.version': 'Version',
    'settings.logout': 'Logout',
    'share.title': 'Share InvenSight',
    'share.urlCopied': 'Share link copied to clipboard!',
    'share.shareLink': 'Share Link',
    'share.copyLink': 'Copy Link',
    'share.invite': 'Invite collaborators via WhatsApp',
    'share.whatsapp': 'Open WhatsApp',
    'login.title': 'Sign In',
    'login.subtitle': 'Sign in to your InvenSight account',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.emailRequired': 'Email is required',
    'login.emailInvalid': 'Please enter a valid email',
    'login.passwordRequired': 'Password is required',
    'login.passwordMin': 'Password must be at least 6 characters',
    'login.signIn': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.registerHere': 'Register here',
    'register.title': 'Create Account',
    'register.subtitle': 'Create your InvenSight account',
    'register.name': 'Full name',
    'register.email': 'Email address',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm password',
    'register.nameRequired': 'Name is required',
    'register.emailRequired': 'Email is required',
    'register.emailInvalid': 'Please enter a valid email',
    'register.passwordRequired': 'Password is required',
    'register.passwordMin': 'Password must be at least 6 characters',
    'register.passwordMatch': 'Passwords do not match',
    'register.createAccount': 'Create Account',
    'register.haveAccount': 'Already have an account?',
    'register.signInHere': 'Sign in here',
    'auth.error': 'Authentication error',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.accountExists': 'An account with this email already exists',
    'modal.close': 'Close',
    'toast.added': 'Item added successfully',
    'toast.updated': 'Item updated successfully',
    'toast.deleted': 'Item deleted successfully',
    'toast.transactionAdded': 'Transaction recorded',
    'toast.journalAdded': 'Journal entry added',
    'toast.restockPredicted': 'Restock prediction calculated',
    'toast.exportPdf': 'PDF exported',
    'toast.exportExcel': 'Excel exported',
  },
  id: {
    'nav.dashboard': 'Dasbor',
    'nav.inventory': 'Inventaris',
    'nav.addItem': 'Tambah Item',
    'nav.analytics': 'Analitik',
    'nav.transactions': 'Transaksi',
    'nav.alerts': 'Peringatan',
    'nav.restock': 'Prediksi Stok',
    'nav.journal': 'Jurnal Keuangan',
    'nav.settings': 'Pengaturan',
    'nav.share': 'Bagikan',
    'common.title': 'InvenSight',
    'common.subtitle': 'Sistem Inventaris & Visibilitas Stok',
    'common.welcome': 'Selamat datang',
    'common.loading': 'Memuat...',
    'common.search': 'Cari...',
    'common.filter': 'Filter',
    'common.export': 'Ekspor',
    'common.add': 'Tambah',
    'common.edit': 'Edit',
    'common.delete': 'Hapus',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.category': 'Kategori',
    'common.location': 'Lokasi',
    'common.supplier': 'Pemasok',
    'common.stock': 'Stok',
    'common.minStock': 'Stok Minimal',
    'common.maxStock': 'Stok Maksimal',
    'common.cost': 'Biaya',
    'common.price': 'Harga',
    'common.totalValue': 'Total Nilai',
    'common.quantity': 'Jumlah',
    'common.date': 'Tanggal',
    'common.action': 'Aksi',
    'common.status': 'Status',
    'common.type': 'Tipe',
    'common.none': 'Tidak ada',
    'common.lowStock': 'Stok Rendah',
    'common.overstock': 'Stok Berlebih',
    'common.expiring': 'Segera Kadaluarsa',
    'common.reorder': 'Reorder Disarankan',
    'dashboard.totalItems': 'Total Item',
    'dashboard.lowStock': 'Item Stok Rendah',
    'dashboard.overstock': 'Item Stok Berlebih',
    'dashboard.totalValue': 'Total Nilai Inventaris',
    'dashboard.expiringSoon': 'Segera Kadaluarsa',
    'dashboard.recentActivity': 'Aktivitas Terbaru',
    'dashboard.restockAlerts': 'Peringatan Restock',
    'inventory.items': 'Item Inventaris',
    'inventory.addNew': 'Tambah Item Baru',
    'inventory.editItem': 'Edit Item',
    'inventory.deleteConfirm': 'Hapus item ini secara permanen?',
    'inventory.stockLevel': 'Level Stok',
    'inventory.low': 'Rendah',
    'inventory.normal': 'Normal',
    'inventory.high': 'Tinggi',
    'inventory.addTransaction': 'Tambah Transaksi',
    'inventory.transactionIn': 'Stok Masuk',
    'inventory.transactionOut': 'Stok Keluar',
    'inventory.transactionAdjust': 'Penyesuaian',
    'inventory.transactionReturn': 'Pengembalian',
    'analytics.title': 'Dasbor Analitik',
    'analytics.stockDistribution': 'Distribusi Stok',
    'analytics.categoryBreakdown': 'Breakdown Kategori',
    'analytics.trends': 'Tren Inventaris',
    'analytics.sourceAttribution': 'Sumber Traffic',
    'analytics.financeSummary': 'Ringkasan Keuangan',
    'analytics.topMoving': 'Item Paling Bergerak',
    'analytics.exportPdf': 'Ekspor Laporan PDF',
    'analytics.exportExcel': 'Ekspor Excel',
    'analytics.noData': 'Tidak ada data',
    'transactions.title': 'Riwayat Transaksi',
    'transactions.add': 'Tambah Transaksi',
    'transactions.filterBy': 'Filter berdasarkan',
    'transactions.allTypes': 'Semua Tipe',
    'transactions.stockIn': 'Stok Masuk',
    'transactions.stockOut': 'Stok Keluar',
    'transactions.adjustment': 'Penyesuaian',
    'transactions.return': 'Pengembalian',
    'alerts.title': 'Pusat Peringatan',
    'alerts.lowStock': 'Peringatan Stok Rendah',
    'alerts.overstock': 'Peringatan Stok Berlebih',
    'alerts.expiring': 'Peringatan Segera Kadaluarsa',
    'alerts.reorder': 'Saran Reorder',
    'alerts.markRead': 'Tandai Dibaca',
    'alerts.markAllRead': 'Tandai Semua Dibaca',
    'alerts.empty': 'Tidak ada peringatan',
    'restock.title': 'Prediksi Restock',
    'restock.predictedDate': 'Prediksi Tanggal Restock',
    'restock.confidence': 'Keyakinan',
    'restock.low': 'Rendah',
    'restock.medium': 'Sedang',
    'restock.high': 'Tinggi',
    'restock.empty': 'Tidak ada prediksi restock',
    'journal.title': 'Jurnal Keuangan',
    'journal.entry': 'Entri Jurnal',
    'journal.addEntry': 'Tambah Entri',
    'journal.source': 'Sumber',
    'journal.description': 'Deskripsi',
    'journal.amount': 'Jumlah',
    'journal.type': 'Tipe',
    'journal.income': 'Pendapatan',
    'journal.expense': 'Pengeluaran',
    'journal.autoTask': 'Auto Tugas',
    'journal.autoBill': 'Auto Tagihan',
    'journal.autoTendor': 'Auto Vendor',
    'journal.manual': 'Manual',
    'journal.posted': 'Diposting',
    'journal.pending': 'Menunggu',
    'journal.cancelled': 'Dibatalkan',
    'journal.totalIncome': 'Total Pendapatan',
    'journal.totalExpense': 'Total Pengeluaran',
    'journal.balance': 'Saldo',
    'journal.exportPdf': 'Ekspor PDF',
    'journal.exportExcel': 'Ekspor Excel',
    'journal.empty': 'Tidak ada entri jurnal',
    'settings.title': 'Pengaturan',
    'settings.theme': 'Tema',
    'settings.language': 'Bahasa',
    'settings.notifications': 'Notifikasi',
    'settings.financeTracking': 'Pelacakan Keuangan',
    'settings.about': 'Tentang',
    'settings.version': 'Versi',
    'settings.logout': 'Keluar',
    'share.title': 'Bagikan InvenSight',
    'share.urlCopied': 'Link bagikan disalin ke clipboard!',
    'share.shareLink': 'Link Bagikan',
    'share.copyLink': 'Salin Link',
    'share.invite': 'Invite kolaborator via WhatsApp',
    'share.whatsapp': 'Buka WhatsApp',
    'login.title': 'Masuk',
    'login.subtitle': 'Masuk ke akun InvenSight Anda',
    'login.email': 'Alamat Email',
    'login.password': 'Kata Sandi',
    'login.emailRequired': 'Email wajib diisi',
    'login.emailInvalid': 'Masukkan email yang valid',
    'login.passwordRequired': 'Kata sandi wajib diisi',
    'login.passwordMin': 'Kata sandi minimal 6 karakter',
    'login.signIn': 'Masuk',
    'login.noAccount': 'Belum punya akun?',
    'login.registerHere': 'Daftar di sini',
    'register.title': 'Buat Akun',
    'register.subtitle': 'Buat akun InvenSight Anda',
    'register.name': 'Nama Lengkap',
    'register.email': 'Alamat Email',
    'register.password': 'Kata Sandi',
    'register.confirmPassword': 'Konfirmasi Kata Sandi',
    'register.nameRequired': 'Nama wajib diisi',
    'register.emailRequired': 'Email wajib diisi',
    'register.emailInvalid': 'Masukkan email yang valid',
    'register.passwordRequired': 'Kata sandi wajib diisi',
    'register.passwordMin': 'Kata sandi minimal 6 karakter',
    'register.passwordMatch': 'Kata sandi tidak cocok',
    'register.createAccount': 'Buat Akun',
    'register.haveAccount': 'Sudah punya akun?',
    'register.signInHere': 'Masuk di sini',
    'auth.error': 'Kesalahan Autentikasi',
    'auth.invalidCredentials': 'Email atau kata sandi tidak valid',
    'auth.accountExists': 'Akun dengan email ini sudah ada',
    'modal.close': 'Tutup',
    'toast.added': 'Item berhasil ditambahkan',
    'toast.updated': 'Item berhasil diperbarui',
    'toast.deleted': 'Item berhasil dihapus',
    'toast.transactionAdded': 'Transaksi tercatat',
    'toast.journalAdded': 'Entri jurnal ditambahkan',
    'toast.restockPredicted': 'Prediksi restock dihitung',
    'toast.exportPdf': 'PDF diekspor',
    'toast.exportExcel': 'Excel diekspor',
  },
};

export function useApp() {
  const [locale, setLocaleState] = useState<Locale>('en');
  const [mounted, setMounted] = useState(false);
  const [t, setT] = useState<Record<string, string>>(translations.en);

  useEffect(() => {
    setMounted(true);
    const stored = localStorage.getItem('invensight_locale') as Locale | null;
    if (stored === 'en' || stored === 'id') setLocaleState(stored);
    const source = localStorage.getItem('invensight_source');
    if (!source && new URLSearchParams(window.location.search).has('utm_source')) {
      localStorage.setItem('invensight_source', new URLSearchParams(window.location.search).get('utm_source')!);
    }
  }, []);

  useEffect(() => {
    if (mounted) {
      setT(translations[locale]);
      localStorage.setItem('invensight_locale', locale);
    }
  }, [locale, mounted]);

  const setLocale = useCallback((l: Locale) => { if (mounted) setLocaleState(l); }, [mounted]);

  const source = mounted ? (localStorage.getItem('invensight_source') || 'direct') : 'direct';

  return { t, locale, setLocale, mounted, source };
}
