export function downloadCSV(data: any[], filename = 'data.csv') {
  const headers = Object.keys(data[0] || {});
  const rows = data.map(row => headers.map(h => {
    const val = row[h];
    if (val === null || val === undefined) return '';
    const str = String(val).replace(/"/g, '""');
    return /[",\n]/.test(str) ? `"${str}"` : str;
  }).join(','));
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export function downloadExcel(data: any[], filename = 'data.xlsx') {
  // Simple HTML table export as .xlsx (works without xlsx library)
  const headers = Object.keys(data[0] || {});
  const html = `<html><head><meta charset="utf-8"></head><body><table><thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${data.map(row => `<tr>${headers.map(h => `<td>${row[h] ?? ''}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`;
  const blob = new Blob([html], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export function downloadPDF(_data: any[], title = 'Document') {
  // Open print dialog as PDF fallback
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  printWindow.document.write(`<html><head><title>${title}</title><style>body{font-family:system-ui;padding:24px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f4f4f5}</style></head><body><h1>${title}</h1><p>Generated by InvenSight — ${new Date().toLocaleString()}</p></body></html>`);
  printWindow.document.close();
  printWindow.print();
}