export const t = {
  en: {
    'app.title': 'InvenSight - Inventory Visibility OS',
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory',
    'nav.orders': 'Orders',
    'nav.suppliers': 'Suppliers',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    'nav.shared': 'Shared Item',
    'nav.share': 'Share',
    'nav.login': 'Sign In',
    'nav.register': 'Register',
    'nav.logout': 'Sign Out',
    'nav.theme': 'Theme',
    'nav.lang': 'Language',
    'nav.card': 'Card',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.emailPlaceholder': 'name@company.com',
    'auth.passwordPlaceholder': 'Min. 6 characters',
    'auth.namePlaceholder': 'John Doe',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Create Account',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUpLink': 'Sign Up',
    'auth.signInLink': 'Sign In',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.emailRequired': 'Email is required',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordMin': 'Password must be at least 6 characters',
    'auth.nameRequired': 'Name is required',
    'auth.emailInvalid': 'Please enter a valid email',
    'dashboard.welcome': 'Welcome back',
    'dashboard.totalProducts': 'Total Products',
    'dashboard.lowStock': 'Low Stock Items',
    'dashboard.pendingOrders': 'Pending Orders',
    'dashboard.totalValue': 'Total Inventory Value',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.restockNeeded': 'Restock Needed',
    'dashboard.outOfStock': 'Out of Stock',
    'dashboard.legend.low': 'Low Stock',
    'dashboard.legend.out': 'Out of Stock',
    'dashboard.legend.good': 'Good Stock',
    'inventory.title': 'Inventory Management',
    'inventory.search': 'Search products...',
    'inventory.addProduct': 'Add Product',
    'inventory.editProduct': 'Edit Product',
    'inventory.deleteProduct': 'Delete Product',
    'inventory.productName': 'Product Name',
    'inventory.sku': 'SKU',
    'inventory.category': 'Category',
    'inventory.quantity': 'Quantity',
    'inventory.price': 'Unit Price (USD)',
    'inventory.location': 'Storage Location',
    'inventory.minStock': 'Min Stock Level',
    'inventory.maxStock': 'Max Stock Level',
    'inventory.supplier': 'Primary Supplier',
    'inventory.lastUpdated': 'Last Updated',
    'inventory.actions': 'Actions',
    'inventory.lowStockWarning': 'Low stock',
    'inventory.outOfStockWarning': 'Out of stock',
    'inventory.goodStock': 'In stock',
    'inventory.confirmDelete': 'Are you sure you want to delete this product?',
    'inventory.saveSuccess': 'Product saved',
    'inventory.deleteSuccess': 'Product deleted',
    'inventory.addSuccess': 'Product added',
    'inventory.nameRequired': 'Product name is required',
    'inventory.skuRequired': 'SKU is required',
    'inventory.quantityRequired': 'Quantity is required',
    'inventory.priceRequired': 'Price is required',
    'inventory.categoryRequired': 'Category is required',
    'inventory.quantityMin': 'Quantity must be 0 or more',
    'inventory.priceMin': 'Price must be 0 or more',
    'inventory.empty': 'No products found',
    'inventory.heatmap': 'Stock Distribution Heatmap',
    'inventory.restockForecast': 'Restock Forecast',
    'inventory.trend': 'Stock Trend (7 days)',
    'inventory.barChart': 'Stock by Category',
    'orders.title': 'Order Management',
    'orders.newOrder': 'New Order',
    'orders.orderId': 'Order ID',
    'orders.supplier': 'Supplier',
    'orders.product': 'Product',
    'orders.quantity': 'Quantity',
    'orders.status': 'Status',
    'orders.date': 'Order Date',
    'orders.total': 'Total',
    'orders.actions': 'Actions',
    'orders.statuspending': 'Pending',
    'orders.statusconfirmed': 'Confirmed',
    'orders.statusreceived': 'Received',
    'orders.statuscancelled': 'Cancelled',
    'orders.statusdelayed': 'Delayed',
    'orders.confirmOrder': 'Confirm Order',
    'orders.receivedOrder': 'Mark Received',
    'orders.cancelOrder': 'Cancel Order',
    'orders.confirmSuccess': 'Order confirmed',
    'orders.receivedSuccess': 'Order marked received',
    'orders.cancelSuccess': 'Order cancelled',
    'orders.empty': 'No orders found',
    'orders.addSuccess': 'Order created',
    'orders.selectProduct': 'Select a product',
    'orders.selectSupplier': 'Select a supplier',
    'orders.quantityMin': 'Quantity must be 1 or more',
    'orders.productRequired': 'Product is required',
    'orders.supplierRequired': 'Supplier is required',
    'suppliers.title': 'Supplier Directory',
    'suppliers.addSupplier': 'Add Supplier',
    'suppliers.editSupplier': 'Edit Supplier',
    'suppliers.deleteSupplier': 'Delete Supplier',
    'suppliers.name': 'Supplier Name',
    'suppliers.email': 'Contact Email',
    'suppliers.phone': 'Phone',
    'suppliers.address': 'Address',
    'suppliers.notes': 'Notes',
    'suppliers.productsSupplied': 'Products Supplied',
    'suppliers.contactPerson': 'Contact Person',
    'suppliers.lastOrder': 'Last Order Date',
    'suppliers.activeOrders': 'Active Orders',
    'suppliers.empty': 'No suppliers found',
    'suppliers.addSuccess': 'Supplier added',
    'suppliers.saveSuccess': 'Supplier saved',
    'suppliers.deleteSuccess': 'Supplier deleted',
    'suppliers.confirmDelete': 'Delete this supplier?',
    'suppliers.nameRequired': 'Supplier name is required',
    'suppliers.emailRequired': 'Email is required',
    'suppliers.emailInvalid': 'Enter a valid email',
    'suppliers.actions': 'Actions',
    'analytics.title': 'Analytics',
    'analytics.inventoryOverview': 'Inventory Overview',
    'analytics.stockValue': 'Total Stock Value',
    'analytics.categoryBreakdown': 'Category Breakdown',
    'analytics.stockLevelDistribution': 'Stock Level Distribution',
    'analytics.monthlyTrend': 'Monthly Trend',
    'analytics.restockAlerts': 'Restock Alerts',
    'analytics.sourceAttribution': 'Traffic Sources',
    'analytics.topProducts': 'Top Products by Value',
    'analytics.movingAvg': 'Moving Average (30d)',
    'analytics.lowStockItems': 'Low Stock Items',
    'analytics.outOfStockItems': 'Out of Stock Items',
    'analytics.totalOrders': 'Total Orders',
    'analytics.pendingOrders': 'Pending Orders',
    'analytics.confirmedOrders': 'Confirmed Orders',
    'analytics.receivedOrders': 'Received Orders',
    'analytics.cancelledOrders': 'Cancelled Orders',
    'analytics.from': 'From',
    'analytics.to': 'To',
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.businessName': 'Business Name',
    'settings.currency': 'Currency',
    'settings.notifications': 'Notifications',
    'settings.enableEmail': 'Enable email notifications',
    'settings.emailAddress': 'Notification Email',
    'settings.shareLink': 'Share Inventory Link',
    'settings.shareGenerated': 'Share link generated',
    'settings.shareCopied': 'Link copied to clipboard',
    'settings.shareFallback': 'Copy this link manually',
    'settings.shareUrl': 'Share URL',
    'settings.shareButton': 'Generate Share Link',
    'settings.shareNote': 'Share a single inventory item publicly',
    'settings.shareExpiration': 'Link expires in 24 hours',
    'settings.shareCopiedManual': 'Link copied',
    'settings.themeLight': 'Light',
    'settings.themeDark': 'Dark',
    'settings.themeSystem': 'System',
    'settings.saved': 'Settings saved',
    'shared.title': 'Shared Inventory Item',
    'shared.notFound': 'Item not found or expired',
    'shared.product': 'Product',
    'shared.qty': 'Quantity',
    'shared.location': 'Location',
    'shared.lastUpdated': 'Last Updated',
    'shared.sharedBy': 'Shared by',
    'shared.expired': 'This link has expired',
    'shared.copyLink': 'Copy Link',
    'shared.linkCopied': 'Link copied',
    'shared.fallback': 'Copy this link manually',
    'shared.shareButton': 'Share',
    'nav.summary': 'Summary',
    'nav.calendar': 'Calendar',
    'nav.export': 'Export',
    'nav.notifications': 'Notifications',
    'export.title': 'Export Data',
    'export.pdfBtn': 'Export PDF',
    'export.xlsxBtn': 'Export Excel',
    'export.pdfSuccess': 'PDF exported',
    'export.xlsxSuccess': 'Excel exported',
    'export.pdfTitle': 'InvenSight Inventory Report',
    'share.title': 'Share Inventory',
    'share.selectItem': 'Select an item to share',
    'share.generate': 'Generate Link',
    'share.linkGenerated': 'Public link generated',
    'share.linkCopied': 'Link copied',
    'share.copyFailed': 'Copy failed — copy manually',
    'share.linkExpired': 'Link expired',
    'share.noItem': 'No item selected',
    'share.copyText': 'Copy',
    'categories.title': 'Categories',
    'categories.addCategory': 'Add Category',
    'categories.name': 'Category Name',
    'categories.color': 'Color',
    'categories.productCount': 'Products',
    'categories.totalStock': 'Total Stock',
    'categories.totalValue': 'Total Value',
    'categories.empty': 'No categories',
    'categories.addSuccess': 'Category added',
    'categories.saveSuccess': 'Category saved',
    'categories.deleteSuccess': 'Category deleted',
    'categories.confirmDelete': 'Delete this category?',
    'categories.nameRequired': 'Category name is required',
    'categories.editSupplier': 'Edit Category',
    'notifications.invalidCredentials': 'Invalid credentials',
    'auth.emailTaken': 'Email already registered',
  },
  id: {
    'app.title': 'InvenSight - Sistem Visibilitas Inventaris',
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventaris',
    'nav.orders': 'Pembelian',
    'nav.suppliers': 'Supplier',
    'nav.analytics': 'Analitik',
    'nav.settings': 'Pengaturan',
    'nav.shared': 'Item Terbagi',
    'nav.share': 'Bagikan',
    'nav.login': 'Masuk',
    'nav.register': 'Daftar',
    'nav.logout': 'Keluar',
    'nav.theme': 'Tema',
    'nav.lang': 'Bahasa',
    'nav.card': 'Kartu',
    'auth.email': 'Email',
    'auth.password': 'Kata Sandi',
    'auth.name': 'Nama Lengkap',
    'auth.emailPlaceholder': 'nama@perusahaan.com',
    'auth.passwordPlaceholder': 'Minimal 6 karakter',
    'auth.namePlaceholder': 'Budi Santoso',
    'auth.signIn': 'Masuk',
    'auth.signUp': 'Buat Akun',
    'auth.noAccount': 'Belum punya akun?',
    'auth.hasAccount': 'Sudah punya akun?',
    'auth.signUpLink': 'Daftar',
    'auth.signInLink': 'Masuk',
    'auth.invalidCredentials': 'Email atau kata sandi tidak valid',
    'auth.emailRequired': 'Email wajib diisi',
    'auth.passwordRequired': 'Kata sandi wajib diisi',
    'auth.passwordMin': 'Kata sandi minimal 6 karakter',
    'auth.nameRequired': 'Nama wajib diisi',
    'auth.emailInvalid': 'Masukkan email yang valid',
    'dashboard.welcome': 'Selamat kembali',
    'dashboard.totalProducts': 'Total Produk',
    'dashboard.lowStock': 'Item Stok Rendah',
    'dashboard.pendingOrders': 'Pembelian Pending',
    'dashboard.totalValue': 'Nilai Total Inventaris',
    'dashboard.recentActivity': 'Aktivitas Terbaru',
    'dashboard.restockNeeded': 'Perlu Pengisian',
    'dashboard.outOfStock': 'Habis',
    'dashboard.legend.low': 'Stok Rendah',
    'dashboard.legend.out': 'Habis',
    'dashboard.legend.good': "Stok Baik",
    'inventory.title': 'Manajemen Inventaris',
    'inventory.search': 'Cari produk...',
    'inventory.addProduct': 'Tambah Produk',
    'inventory.editProduct': 'Edit Produk',
    'inventory.deleteProduct': 'Hapus Produk',
    'inventory.productName': 'Nama Produk',
    'inventory.sku': 'SKU',
    'inventory.category': 'Kategori',
    'inventory.quantity': 'Jumlah',
    'inventory.price': 'Harga Satuan (USD)',
    'inventory.location': 'Lokasi Penyimpanan',
    'inventory.minStock': 'Minimum Stok',
    'inventory.maxStock': 'Maksimum Stok',
    'inventory.supplier': 'Supplier Utama',
    'inventory.lastUpdated': 'Terakhir Diperbarui',
    'inventory.actions': 'Aksi',
    'inventory.lowStockWarning': 'Stok rendah',
    'inventory.outOfStockWarning': 'Habis',
    'inventory.goodStock': 'Tersedia',
    'inventory.confirmDelete': 'Yakin ingin menghapus produk ini?',
    'inventory.saveSuccess': 'Produk disimpan',
    'inventory.deleteSuccess': 'Produk dihapus',
    'inventory.addSuccess': 'Produk ditambahkan',
    'inventory.nameRequired': 'Nama produk wajib diisi',
    'inventory.skuRequired': 'SKU wajib diisi',
    'inventory.quantityRequired': 'Jumlah wajib diisi',
    'inventory.priceRequired': 'Harga wajib diisi',
    'inventory.categoryRequired': 'Kategori wajib diisi',
    'inventory.quantityMin': 'Jumlah harus 0 atau lebih',
    'inventory.priceMin': 'Harga harus 0 atau lebih',
    'inventory.empty': 'Tidak ada produk',
    'inventory.heatmap': 'Peta Panas Distribusi Stok',
    'inventory.restockForecast': 'Prediksi Pengisian Stok',
    'inventory.trend': 'Tren Stok (7 hari)',
    'inventory.barChart': 'Stok per Kategori',
    'orders.title': 'Manajemen Pembelian',
    'orders.newOrder': 'Pembelian Baru',
    'orders.orderId': 'ID Pesanan',
    'orders.supplier': 'Supplier',
    'orders.product': 'Produk',
    'orders.quantity': 'Jumlah',
    'orders.status': 'Status',
    'orders.date': 'Tanggal',
    'orders.total': 'Total',
    'orders.actions': 'Aksi',
    'orders.statuspending': 'Pending',
    'orders.statusconfirmed': 'Dikonfirmasi',
    'orders.statusreceived': 'Diterima',
    'orders.statuscancelled': 'Dibatalkan',
    'orders.statusdelayed': 'Terlambat',
    'orders.confirmOrder': 'Konfirmasi',
    'orders.receivedOrder': 'Tandai Terima',
    'orders.cancelOrder': 'Batal',
    'orders.confirmSuccess': 'Pesanan dikonfirmasi',
    'orders.receivedSuccess': 'Pesanan tandai diterima',
    'orders.cancelSuccess': 'Pesanan dibatalkan',
    'orders.empty': 'Tidak ada pesanan',
    'orders.addSuccess': 'Pesanan dibuat',
    'orders.selectProduct': 'Pilih produk',
    'orders.selectSupplier': 'Pilih supplier',
    'orders.quantityMin': 'Jumlah harus 1 atau lebih',
    'orders.productRequired': 'Produk wajib dipilih',
    'orders.supplierRequired': 'Supplier wajib dipilih',
    'suppliers.title': 'Direktori Supplier',
    'suppliers.addSupplier': 'Tambah Supplier',
    'suppliers.editSupplier': 'Edit Supplier',
    'suppliers.deleteSupplier': 'Hapus Supplier',
    'suppliers.name': 'Nama Supplier',
    'suppliers.email': 'Email Kontak',
    'suppliers.phone': 'Telepon',
    'suppliers.address': 'Alamat',
    'suppliers.notes': 'Catatan',
    'suppliers.productsSupplied': 'Produk yang Disediakan',
    'suppliers.contactPerson': 'Penanggung Jawab',
    'suppliers.lastOrder': 'Pembelian Terakhir',
    'suppliers.activeOrders': 'Pesanan Aktif',
    'suppliers.empty': 'Tidak ada supplier',
    'suppliers.addSuccess': 'Supplier ditambahkan',
    'suppliers.saveSuccess': 'Supplier disimpan',
    'suppliers.deleteSuccess': 'Supplier dihapus',
    'suppliers.confirmDelete': 'Hapus supplier ini?',
    'suppliers.nameRequired': 'Nama supplier wajib diisi',
    'suppliers.emailRequired': 'Email wajib diisi',
    'suppliers.emailInvalid': 'Masukkan email yang valid',
    'suppliers.actions': 'Aksi',
    'analytics.title': 'Analitik',
    'analytics.inventoryOverview': 'Ikhtisar Inventaris',
    'analytics.stockValue': 'Nilai Total Stok',
    'analytics.categoryBreakdown': 'Breakdown Kategori',
    'analytics.stockLevelDistribution': 'Distribusi Level Stok',
    'analytics.monthlyTrend': 'Tren Bulanan',
    'analytics.restockAlerts': 'Peringatan Pengisian',
    'analytics.sourceAttribution': 'Sumber Traffic',
    'analytics.topProducts': 'Produk Teratas berdasarkan Nilai',
    'analytics.movingAvg': 'Rata-Rata Bergerak (30 hari)',
    'analytics.lowStockItems': 'Item Stok Rendah',
    'analytics.outOfStockItems': 'Item Habis',
    'analytics.totalOrders': 'Total Pembelian',
    'analytics.pendingOrders': 'Pending',
    'analytics.confirmedOrders': 'Dikonfirmasi',
    'analytics.receivedOrders': 'Diterima',
    'analytics.cancelledOrders': 'Dibatalkan',
    'analytics.from': 'Dari',
    'analytics.to': 'Sampai',
    'settings.title': 'Pengaturan',
    'settings.profile': 'Profil',
    'settings.businessName': 'Nama Bisnis',
    'settings.currency': 'Mata Uang',
    'settings.notifications': 'Notifikasi',
    'settings.enableEmail': 'Aktifkan notifikasi email',
    'settings.emailAddress': 'Email Notifikasi',
    'settings.shareLink': 'Bagikan Tautan Inventaris',
    'settings.shareGenerated': 'Tautan bagikan dibuat',
    'settings.shareCopied': 'Tautan disalin',
    'settings.shareFallback': 'Salin tautan secara manual',
    'settings.shareUrl': 'Tautan Bagikan',
    'settings.shareButton': 'Buat Tautan Bagikan',
    'settings.shareNote': 'Bagikan satu item inventaris secara publik',
    'settings.shareExpiration': 'Tautan kadaluarsa dalam 24 jam',
    'settings.shareCopiedManual': 'Tautan disalin',
    'settings.themeLight': 'Terang',
    'settings.themeDark': 'Gelap',
    'settings.themeSystem': 'Sistem',
    'settings.saved': 'Pengaturan disimpan',
    'shared.title': 'Item Inventaris Terbagi',
    'shared.notFound': 'Item tidak ditemukan atau sudah kadaluarsa',
    'shared.product': 'Produk',
    'shared.qty': 'Jumlah',
    'shared.location': 'Lokasi',
    'shared.lastUpdated': 'Terakhir Diperbarui',
    'shared.sharedBy': 'Dibagikan oleh',
    'shared.expired': 'Tautan ini sudah kadaluarsa',
    'shared.copyLink': 'Salin Tautan',
    'shared.linkCopied': 'Tautan disalin',
    'shared.fallback': 'Salin tautan secara manual',
    'shared.shareButton': 'Bagikan',
    'nav.summary': 'Ringkasan',
    'nav.calendar': 'Kalender',
    'nav.export': 'Ekspor',
    'nav.notifications': 'Notifikasi',
    'export.title': 'Ekspor Data',
    'export.pdfBtn': 'Ekspor PDF',
    'export.xlsxBtn': 'Ekspor Excel',
    'export.pdfSuccess': 'PDF diekspor',
    'export.xlsxSuccess': 'Excel diekspor',
    'export.pdfTitle': 'Laporan Inventaris InvenSight',
    'share.title': 'Bagikan Inventaris',
    'share.selectItem': 'Pilih item untuk dibagikan',
    'share.generate': 'Buat Tautan',
    'share.linkGenerated': 'Tautan publik dibuat',
    'share.linkCopied': 'Tautan disalin',
    'share.copyFailed': 'Gagal salin — salin manual',
    'share.linkExpired': 'Tautan kadaluarsa',
    'share.noItem': 'Tidak ada item terpilih',
    'share.copyText': 'Salin',
    'categories.title': 'Kategori',
    'categories.addCategory': 'Tambah Kategori',
    'categories.name': 'Nama Kategori',
    'categories.color': 'Warna',
    'categories.productCount': 'Produk',
    'categories.totalStock': 'Total Stok',
    'categories.totalValue': 'Total Nilai',
    'categories.empty': 'Tidak ada kategori',
    'categories.addSuccess': 'Kategori ditambahkan',
    'categories.saveSuccess': 'Kategori disimpan',
    'categories.deleteSuccess': 'Kategori dihapus',
    'categories.confirmDelete': 'Hapus kategori ini?',
    'categories.nameRequired': 'Nama kategori wajib diisi',
    'categories.editSupplier': 'Edit Kategori',
    'notifications.invalidCredentials': 'Kredensial tidak valid',
    'auth.emailTaken': 'Email sudah terdaftar',
  },
};
